name: mern-app

services:

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-app
    ports: 
      - "5000:5000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-app
    ports: 
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - api
    
networks:
  mern-app:
    driver: bridge